######################## default configuration ####################
baseURL = "https://mwrm2023.org"
title = "2023 Joint Midwest - Great Lakes Regional Meeting"
theme = "vixcon-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
# disqusShortname = "vixcon" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [true] # desable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "Schedule"
  URL = "schedule"
  weight = 2
    
  [[menu.main]]
  name = "Expo & Sponsors"
  URL = "exposition"
  weight = 3

  [[menu.main]]
  name = "Awards"
  URL = "awards"
  weight = 4
  
  [[menu.main]]
  name = "FAQ"
  URL = "travel"
  weight = 5
  
  #[[menu.main]]
  #name = "About"
  #URL = "about"
  #weight = 7

  #[[menu.main]]
  #weight = 9
  #name = "Pages"
  #hasChildren = true

    #[[menu.main]]
    #parent = "Pages"
    #name = "Tickets"
    #URL = "pricing"

    #[[menu.main]]
    #parent = "Pages"
    #name = "Blog"
    #URL = "blog"

    #[[menu.main]]
    #parent = "Pages"
    #name = "FAQ"
    #URL = "faq"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 10

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Informational website for the 2023 Joint MRWM and GLRM"
author = "DrLabRatOry"
# email address
email = "info@mwrm2023.org"
# contact form action
contact_form_action = "https://formspree.io/f/xjvdlawl" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "G-6V8SMMHHZY" # your id
# search for blog page
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Register"
link = "pricing"


# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "38.76922324639817"
map_longitude = "-90.50110566536821"
map_marker = "images/marker.png"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/AmericanChemicalSociety"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/AmerChemSociety"

[[params.social]]
icon = "tf-ion-social-linkedin"
link = "https://www.linkedin.com/groups/51209/"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "The 2023 Joint Midwest Regional Meeting and Great Lakes Regional Meeting is organized by the St. Louis and East Central Illinois sections of the American Chemical Society"
# copyright
copyright = "Copyright &copy; 2023"